### ISSUE TITLE
Including logger metadata in the TFDS backend.

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/envlogger#6]
Hi,

It looks like the TFDS backend does not support recording metadata from envlogger. It would be very useful for having this feature. I think there is a metadata key tfds DatasetConfig that we might be able to use for that.

I am happy to investigate this and create a PR.

**Comment by kenjitoyama** [comment]
Hello @ethanluoyc, did you try [`store_ds_metadata`](https://github.com/deepmind/envlogger/blob/1c0d8f29c114128e75573ea7a605eeb0548ca29b/envlogger/backends/tfds_backend_writer.py#L86)? It does end up in TFDS and it can be retrieved later (please see this [unit test](https://github.com/deepmind/envlogger/blob/1c0d8f29c114128e75573ea7a605eeb0548ca29b/envlogger/backends/tfds_backend_writer_test.py#L165)).

**Comment by ethanluoyc** [comment]
I didin't see that argument! Thanks for letting me know! Sorry for not noticing this. Closing.
